services:
#    vdm_scrapper.example:
#        class: VDM\ScrapperBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    vdm_scrapper.vdmpostsupdater:
        class: VDM\ScrapperBundle\Service\VDMPostsUpdater
        arguments: [ @doctrine.orm.entity_manager ]