<?php

namespace VDM\ScrapperBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VDMPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VDMPostRepository extends EntityRepository
{
	// we define a custom findById function to get result as array
	public function getVDMPostById ($id)
	{
		$qb = $this->createQueryBuilder('v');

		$qb->where('v.id = :id')
			->setParameter('id', $id)
			->orderBy('v.date', 'DESC');
			
		return $qb
			->getQuery()
			->getArrayResult()
			;
	}
	
	public function getVDMPostsWithCriteria ($author, $from, $to)
	{
		$qb = $this->createQueryBuilder('v');

		// filtres optionnels
		if (! is_null($author)) {
			$qb->andwhere('v.author = :author')
				->setParameter('author', $author)
			;
		}
		if (! is_null($from)) {
			$qb->andwhere('v.date >= :from')
				->setParameter('from', $from)
			;
		}
		if (! is_null($to)) {
			$qb->andwhere('v.date <= :to')
				->setParameter('to', $to)
			;
		}

		$qb->orderBy('v.date', 'DESC');

		return $qb
			->getQuery()
			->getArrayResult()
		;
	}
}
